CREATE TYPE "ShipmentStatus" AS ENUM ('CREATED','PICKED_UP','IN_TRANSIT','DELIVERED','CANCELLED','FAILED');
CREATE TYPE "ProcessingState" AS ENUM ('PENDING','PROCESSING','COMPLETED','FAILED');
CREATE TYPE "BatchStatus" AS ENUM ('PROCESSING','COMPLETED','PARTIALLY_COMPLETED','FAILED');
CREATE TYPE "BatchItemStatus" AS ENUM ('PENDING','PROCESSING','SUCCESS','FAILED');
CREATE TABLE "orders" ("id" UUID PRIMARY KEY,"order_id" TEXT NOT NULL UNIQUE,"courier_partner" TEXT NOT NULL,"courier_order_id" TEXT,"awb_number" TEXT,"shipment_status" "ShipmentStatus" NOT NULL DEFAULT 'CREATED',"processing_state" "ProcessingState" NOT NULL DEFAULT 'PENDING',"normalized_request" JSONB NOT NULL,"request_hash" TEXT NOT NULL,"courier_request_payload" JSONB,"courier_response_payload" JSONB,"failure_code" TEXT,"failure_reason" TEXT,"created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" TIMESTAMP(3) NOT NULL);
CREATE TABLE "tracking_events" ("id" UUID PRIMARY KEY,"order_ref" UUID NOT NULL REFERENCES "orders"("id") ON DELETE CASCADE,"status" "ShipmentStatus" NOT NULL,"courier_status" TEXT,"raw_payload" JSONB NOT NULL,"event_timestamp" TIMESTAMP(3) NOT NULL,"event_fingerprint" TEXT NOT NULL,"created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE("order_ref","event_fingerprint"));
CREATE TABLE "bulk_batches" ("id" UUID PRIMARY KEY,"batch_id" TEXT NOT NULL UNIQUE,"status" "BatchStatus" NOT NULL DEFAULT 'PROCESSING',"total_orders" INTEGER NOT NULL,"completed_orders" INTEGER NOT NULL DEFAULT 0,"successful_orders" INTEGER NOT NULL DEFAULT 0,"failed_orders" INTEGER NOT NULL DEFAULT 0,"created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" TIMESTAMP(3) NOT NULL);
CREATE TABLE "bulk_batch_items" ("id" UUID PRIMARY KEY,"batch_ref" UUID NOT NULL REFERENCES "bulk_batches"("id") ON DELETE CASCADE,"order_id" TEXT NOT NULL,"courier_partner" TEXT NOT NULL,"status" "BatchItemStatus" NOT NULL DEFAULT 'PENDING',"order_ref" UUID REFERENCES "orders"("id") ON DELETE SET NULL,"error_code" TEXT,"error_message" TEXT,"created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" TIMESTAMP(3) NOT NULL,UNIQUE("batch_ref","order_id"));
CREATE INDEX "orders_courier_partner_idx" ON "orders"("courier_partner"); CREATE INDEX "orders_awb_number_idx" ON "orders"("awb_number"); CREATE INDEX "tracking_events_order_ref_event_timestamp_idx" ON "tracking_events"("order_ref","event_timestamp"); CREATE INDEX "bulk_batch_items_order_id_idx" ON "bulk_batch_items"("order_id");
